name: PR Workflow

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, edited, closed]
    branches:
      - main

jobs:
  build:
    name: Build, Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build the package
        run: npm run build

      - name: Lint the package
        run: npm run lint
